In [ ]:
## Urban_startup_orders data

In [3]:
## Import library & data and data quality check
import pandas as pd
import numpy as np

df = pd.read_csv("urbanleaf_startup_orders.csv")
df

,order_id,order_date,customer_id,customer_age,gender,customer_segment,city,state,product_id,product_name,category,quantity,unit_price_inr,original_unit_price_inr,discount_percent,discount_amount_inr,shipping_cost_inr,order_value_inr,total_amount_inr,payment_mode,sales_channel,acquisition_source,order_status,delivery_date,delivery_days,customer_rating
0,ORD000001,2025-01-01,CUST00111,29,Male,New,Bengaluru,Karnataka,P001,Reusable Water Bottle,Lifestyle,1,299,499,10,29.90,60,269.10,329.10,Cash on Delivery,Website,Instagram Ads,Delivered,2025-01-06,5.0,4.0
1,ORD000002,2025-01-01,CUST00076,36,Female,Loyal,Jaipur,Rajasthan,P004,Scented Candle,Home & Office,1,249,399,15,37.35,50,211.65,261.65,Cash on Delivery,WhatsApp,Referral,Delivered,2025-01-07,6.0,NaN
2,ORD000003,2025-01-01,CUST00111,29,Male,New,Bengaluru,Karnataka,P001,Reusable Water Bottle,Lifestyle,2,299,499,0,0.00,50,598.00,648.00,Debit Card,Instagram,Organic Search,Delivered,2025-01-03,2.0,4.0
3,ORD000004,2025-01-01,CUST00111,29,Male,New,Bengaluru,Karnataka,P001,Reusable Water Bottle,Lifestyle,2,299,499,5,29.90,50,568.10,618.10,Debit Card,Marketplace,Direct,Delivered,2025-01-05,4.0,4.0
4,ORD000005,2025-01-02,CUST00391,23,Female,New,Jaipur,Rajasthan,P008,Travel Pouch,Accessories,1,329,499,5,16.45,60,312.55,372.55,Net Banking,Website,Organic Search,Delivered,2025-01-05,3.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,ORD001496,2025-12-29,CUST00340,21,Prefer not to say,New,Lucknow,Uttar Pradesh,P006,Notebook Set,Stationery,1,179,299,5,8.95,50,170.05,220.05,Debit Card,Marketplace,Referral,Shipped,NaN,NaN,NaN
1496,ORD001497,2025-12-29,CUST00302,29,Female,Returning,Surat,Gujarat,P009,Ceramic Mug,Home & Office,1,279,449,10,27.90,60,251.10,311.10,Credit Card,Instagram,Instagram Ads,Delivered,2026-01-03,5.0,5.0
1497,ORD001498,2025-12-29,CUST00312,24,Female,New,Bengaluru,Karnataka,P004,Scented Candle,Home & Office,2,249,399,15,74.70,60,423.30,483.30,UPI,Website,Instagram Ads,Processing,NaN,NaN,NaN
1498,ORD001499,2025-12-30,CUST00063,22,Male,Returning,Kota,Rajasthan,P011,Resistance Band Set,Fitness,1,499,799,15,74.85,50,424.15,474.15,Net Banking,Instagram,Organic Search,Delivered,2026-01-06,7.0,4.0
1499,ORD001500,2025-12-31,CUST00673,28,Female,Returning,Delhi,Delhi,P001,Reusable Water Bottle,Lifestyle,1,299,499,20,59.80,0,239.20,239.20,Cash on Delivery,Instagram,Instagram Ads,Delivered,2026-01-05,5.0,NaN

In [2]:
pd.set_option('display.max_columns',None)

In [7]:
# Dataset dimensions
print("Shape:", df.shape)

Shape: (1500, 26)

In [8]:
# Column names and data types
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 26 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   order_id                 1500 non-null   object
 1   order_date               1500 non-null   object
 2   customer_id              1500 non-null   object
 3   customer_age             1500 non-null   int64
 4   gender                   1500 non-null   object
 5   customer_segment         1500 non-null   object
 6   city                     1500 non-null   object
 7   state                    1500 non-null   object
 8   product_id               1500 non-null   object
 9   product_name             1500 non-null   object
 10  category                 1500 non-null   object
 11  quantity                 1500 non-null   int64
 12  unit_price_inr           1500 non-null   int64
 13  original_unit_price_inr  1500 non-null   int64
 14  discount_percent         1500 non-null   int64
 15  discount_amount_inr      1500 non-null   float64
 16  shipping_cost_inr        1500 non-null   int64
 17  order_value_inr          1500 non-null   float64
 18  total_amount_inr         1500 non-null   float64
 19  payment_mode             1500 non-null   object
 20  sales_channel            1500 non-null   object
 21  acquisition_source       1500 non-null   object
 22  order_status             1500 non-null   object
 23  delivery_date            1273 non-null   object
 24  delivery_days            1273 non-null   float64
 25  customer_rating          905 non-null    float64
dtypes: float64(5), int64(6), object(15)
memory usage: 304.8+ KB
None

In [9]:
# Missing values
print(df.isnull().sum())

order_id                     0
order_date                   0
customer_id                  0
customer_age                 0
gender                       0
customer_segment             0
city                         0
state                        0
product_id                   0
product_name                 0
category                     0
quantity                     0
unit_price_inr               0
original_unit_price_inr      0
discount_percent             0
discount_amount_inr          0
shipping_cost_inr            0
order_value_inr              0
total_amount_inr             0
payment_mode                 0
sales_channel                0
acquisition_source           0
order_status                 0
delivery_date              227
delivery_days              227
customer_rating            595
dtype: int64

In [10]:
# Duplicate rows
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [12]:
# Duplicate order IDs
print("Duplicate order IDs:", df["order_id"].duplicated().sum())

Duplicate order IDs: 0

In [13]:
# Unique customers
print("Unique customers:", df["customer_id"].nunique())

Unique customers: 511

In [14]:
# Order status
print(df["order_status"].value_counts())

order_status
Delivered     1215
Cancelled      100
Shipped         81
Returned        58
Processing      46
Name: count, dtype: int64

In [15]:
# Customer segment
print(df["customer_segment"].value_counts())

customer_segment
Returning    630
New          583
Loyal        287
Name: count, dtype: int64

In [16]:
df.describe()

,customer_age,quantity,unit_price_inr,original_unit_price_inr,discount_percent,discount_amount_inr,shipping_cost_inr,order_value_inr,total_amount_inr,delivery_days,customer_rating
count,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1273.000000,905.000000
mean,29.908667,1.450000,318.766667,501.300000,8.590000,39.478100,44.693333,423.831900,468.525233,4.425766,3.899448
std,7.606591,0.715431,119.316539,167.973768,6.262698,41.816017,22.382432,276.531732,277.902324,1.856748,1.055878
min,18.000000,1.000000,179.000000,299.000000,0.000000,0.000000,0.000000,143.200000,143.200000,1.000000,1.000000
25%,24.000000,1.000000,229.000000,349.000000,0.000000,0.000000,40.000000,229.000000,274.100000,3.000000,3.000000
50%,29.000000,1.000000,279.000000,449.000000,10.000000,29.900000,50.000000,338.300000,386.300000,4.000000,4.000000
75%,35.000000,2.000000,399.000000,599.000000,15.000000,54.900000,60.000000,508.300000,559.000000,6.000000,5.000000
max,60.000000,4.000000,549.000000,799.000000,20.000000,329.400000,80.000000,2196.000000,2246.000000,9.000000,5.000000

In [21]:
df[['customer_id','gender','customer_age','category','customer_rating','discount_percent','payment_mode','order_status']].head(20)

,customer_id,gender,customer_age,category,customer_rating,discount_percent,payment_mode,order_status
0,CUST00111,Male,29,Lifestyle,4.0,10,Cash on Delivery,Delivered
1,CUST00076,Female,36,Home & Office,NaN,15,Cash on Delivery,Delivered
2,CUST00111,Male,29,Lifestyle,4.0,0,Debit Card,Delivered
3,CUST00111,Male,29,Lifestyle,4.0,5,Debit Card,Delivered
4,CUST00391,Female,23,Accessories,NaN,5,Net Banking,Delivered
5,CUST00465,Male,31,Stationery,4.0,20,UPI,Delivered
6,CUST00118,Female,23,Accessories,NaN,5,UPI,Delivered
7,CUST00565,Male,25,Home & Office,NaN,10,UPI,Delivered
8,CUST00565,Male,25,Accessories,NaN,20,Debit Card,Delivered
9,CUST00565,Male,25,Lifestyle,5.0,10,Debit Card,Delivered
10,CUST00321,Female,35,Lifestyle,3.0,10,Debit Card,Delivered
11,CUST00384,Female,29,Accessories,NaN,10,UPI,Delivered
12,CUST00486,Female,21,Home & Office,2.0,0,Cash on Delivery,Delivered
13,CUST00096,Female,38,Fitness,4.0,10,UPI,Delivered
14,CUST00382,Prefer not to say,32,Accessories,NaN,5,Debit Card,Returned
15,CUST00601,Male,18,Accessories,NaN,10,Credit Card,Shipped
16,CUST00576,Female,34,Home & Office,NaN,0,Debit Card,Shipped
17,CUST00111,Male,29,Accessories,5.0,0,Debit Card,Delivered
18,CUST00434,Female,23,Home & Office,NaN,0,Cash on Delivery,Delivered
19,CUST00295,Female,31,Stationery,4.0,5,UPI,Delivered

In [36]:
df.groupby('gender')['customer_rating'].mean()

gender
Female    3.958042
Male      3.850340
Unknow    3.800000
Name: customer_rating, dtype: float64

In [33]:
df[df['customer_id'] == 'CUST00402']

,order_id,order_date,customer_id,customer_age,gender,customer_segment,city,state,product_id,product_name,category,quantity,unit_price_inr,original_unit_price_inr,discount_percent,discount_amount_inr,shipping_cost_inr,order_value_inr,total_amount_inr,payment_mode,sales_channel,acquisition_source,order_status,delivery_date,delivery_days,customer_rating
91,ORD000092,2025-01-26,CUST00402,28,Unknow,Returning,Jaipur,Rajasthan,P005,Steel Lunch Box,Lifestyle,2,549,799,15,164.7,40,933.3,973.3,UPI,Marketplace,Direct,Delivered,2025-02-01,6.0,5.0
1449,ORD001450,2025-12-19,CUST00402,28,Unknow,Returning,Jaipur,Rajasthan,P009,Ceramic Mug,Home & Office,2,279,449,10,55.8,0,502.2,502.2,Debit Card,Marketplace,Direct,Shipped,NaN,NaN,NaN

In [34]:
df[df['gender'] == 'Unknow']

,order_id,order_date,customer_id,customer_age,gender,customer_segment,city,state,product_id,product_name,category,quantity,unit_price_inr,original_unit_price_inr,discount_percent,discount_amount_inr,shipping_cost_inr,order_value_inr,total_amount_inr,payment_mode,sales_channel,acquisition_source,order_status,delivery_date,delivery_days,customer_rating
14,ORD000015,2025-01-05,CUST00382,32,Unknow,Returning,Lucknow,Uttar Pradesh,P007,Minimal Wallet,Accessories,1,399,599,5,19.95,50,379.05,429.05,Debit Card,Website,Organic Search,Returned,2025-01-11,6.0,NaN
70,ORD000071,2025-01-20,CUST00606,18,Unknow,Returning,Indore,Madhya Pradesh,P011,Resistance Band Set,Fitness,2,499,799,5,49.90,60,948.10,1008.10,Cash on Delivery,Website,Instagram Ads,Delivered,2025-01-27,7.0,3.0
91,ORD000092,2025-01-26,CUST00402,28,Unknow,Returning,Jaipur,Rajasthan,P005,Steel Lunch Box,Lifestyle,2,549,799,15,164.70,40,933.30,973.30,UPI,Marketplace,Direct,Delivered,2025-02-01,6.0,5.0
152,ORD000153,2025-02-08,CUST00324,32,Unknow,New,Delhi,Delhi,P008,Travel Pouch,Accessories,2,329,499,10,65.80,40,592.20,632.20,Credit Card,Marketplace,Instagram Ads,Cancelled,NaN,NaN,NaN
182,ORD000183,2025-02-16,CUST00220,35,Unknow,Returning,Hyderabad,Telangana,P002,Cotton Tote Bag,Accessories,1,199,349,0,0.00,0,199.00,199.00,Credit Card,Website,Instagram Ads,Processing,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1416,ORD001417,2025-12-11,CUST00324,32,Unknow,New,Delhi,Delhi,P011,Resistance Band Set,Fitness,1,499,799,15,74.85,60,424.15,484.15,Debit Card,Website,Referral,Shipped,NaN,NaN,NaN
1449,ORD001450,2025-12-19,CUST00402,28,Unknow,Returning,Jaipur,Rajasthan,P009,Ceramic Mug,Home & Office,2,279,449,10,55.80,0,502.20,502.20,Debit Card,Marketplace,Direct,Shipped,NaN,NaN,NaN
1458,ORD001459,2025-12-20,CUST00606,18,Unknow,Returning,Indore,Madhya Pradesh,P007,Minimal Wallet,Accessories,1,399,599,15,59.85,60,339.15,399.15,Credit Card,Instagram,Direct,Delivered,2025-12-24,4.0,5.0
1474,ORD001475,2025-12-24,CUST00113,31,Unknow,New,Jaipur,Rajasthan,P001,Reusable Water Bottle,Lifestyle,1,299,499,15,44.85,50,254.15,304.15,Credit Card,Website,Direct,Cancelled,NaN,NaN,NaN
1495,ORD001496,2025-12-29,CUST00340,21,Unknow,New,Lucknow,Uttar Pradesh,P006,Notebook Set,Stationery,1,179,299,5,8.95,50,170.05,220.05,Debit Card,Marketplace,Referral,Shipped,NaN,NaN,NaN

In [31]:
df.replace({"Prefer not to say": "Unknow"}, inplace = True)

In [37]:
df["gender"].value_counts()

gender
Female    721
Male      717
Unknow     62
Name: count, dtype: int64

In [40]:
df.groupby('order_status')['customer_rating'].count()

order_status
Cancelled       0
Delivered     866
Processing      0
Returned       39
Shipped         0
Name: customer_rating, dtype: int64

In [41]:
df_sample = df.copy()

In [44]:
df_sample['Cancelled_order'] = (df_sample['order_status'] == 'Cancelled').astype(int)
df_sample['Processing_order'] = (df_sample['order_status'] == 'Processing').astype(int)
df_sample['Shipped_order'] = (df_sample['order_status'] == 'Shipped').astype(int)

In [45]:
df_sample

,order_id,order_date,customer_id,customer_age,gender,customer_segment,city,state,product_id,product_name,category,quantity,unit_price_inr,original_unit_price_inr,discount_percent,discount_amount_inr,shipping_cost_inr,order_value_inr,total_amount_inr,payment_mode,sales_channel,acquisition_source,order_status,delivery_date,delivery_days,customer_rating,Cancelled_order,Processing_order,Shipped_order
0,ORD000001,2025-01-01,CUST00111,29,Male,New,Bengaluru,Karnataka,P001,Reusable Water Bottle,Lifestyle,1,299,499,10,29.90,60,269.10,329.10,Cash on Delivery,Website,Instagram Ads,Delivered,2025-01-06,5.0,4.0,0,0,0
1,ORD000002,2025-01-01,CUST00076,36,Female,Loyal,Jaipur,Rajasthan,P004,Scented Candle,Home & Office,1,249,399,15,37.35,50,211.65,261.65,Cash on Delivery,WhatsApp,Referral,Delivered,2025-01-07,6.0,NaN,0,0,0
2,ORD000003,2025-01-01,CUST00111,29,Male,New,Bengaluru,Karnataka,P001,Reusable Water Bottle,Lifestyle,2,299,499,0,0.00,50,598.00,648.00,Debit Card,Instagram,Organic Search,Delivered,2025-01-03,2.0,4.0,0,0,0
3,ORD000004,2025-01-01,CUST00111,29,Male,New,Bengaluru,Karnataka,P001,Reusable Water Bottle,Lifestyle,2,299,499,5,29.90,50,568.10,618.10,Debit Card,Marketplace,Direct,Delivered,2025-01-05,4.0,4.0,0,0,0
4,ORD000005,2025-01-02,CUST00391,23,Female,New,Jaipur,Rajasthan,P008,Travel Pouch,Accessories,1,329,499,5,16.45,60,312.55,372.55,Net Banking,Website,Organic Search,Delivered,2025-01-05,3.0,NaN,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,ORD001496,2025-12-29,CUST00340,21,Unknow,New,Lucknow,Uttar Pradesh,P006,Notebook Set,Stationery,1,179,299,5,8.95,50,170.05,220.05,Debit Card,Marketplace,Referral,Shipped,NaN,NaN,NaN,0,0,1
1496,ORD001497,2025-12-29,CUST00302,29,Female,Returning,Surat,Gujarat,P009,Ceramic Mug,Home & Office,1,279,449,10,27.90,60,251.10,311.10,Credit Card,Instagram,Instagram Ads,Delivered,2026-01-03,5.0,5.0,0,0,0
1497,ORD001498,2025-12-29,CUST00312,24,Female,New,Bengaluru,Karnataka,P004,Scented Candle,Home & Office,2,249,399,15,74.70,60,423.30,483.30,UPI,Website,Instagram Ads,Processing,NaN,NaN,NaN,0,1,0
1498,ORD001499,2025-12-30,CUST00063,22,Male,Returning,Kota,Rajasthan,P011,Resistance Band Set,Fitness,1,499,799,15,74.85,50,424.15,474.15,Net Banking,Instagram,Organic Search,Delivered,2026-01-06,7.0,4.0,0,0,0
1499,ORD001500,2025-12-31,CUST00673,28,Female,Returning,Delhi,Delhi,P001,Reusable Water Bottle,Lifestyle,1,299,499,20,59.80,0,239.20,239.20,Cash on Delivery,Instagram,Instagram Ads,Delivered,2026-01-05,5.0,NaN,0,0,0

In [46]:
# Successful delivered purchases
delivered_df = df[df["order_status"] == "Delivered"].copy()

In [47]:
delivered_df

,order_id,order_date,customer_id,customer_age,gender,customer_segment,city,state,product_id,product_name,category,quantity,unit_price_inr,original_unit_price_inr,discount_percent,discount_amount_inr,shipping_cost_inr,order_value_inr,total_amount_inr,payment_mode,sales_channel,acquisition_source,order_status,delivery_date,delivery_days,customer_rating
0,ORD000001,2025-01-01,CUST00111,29,Male,New,Bengaluru,Karnataka,P001,Reusable Water Bottle,Lifestyle,1,299,499,10,29.90,60,269.10,329.10,Cash on Delivery,Website,Instagram Ads,Delivered,2025-01-06,5.0,4.0
1,ORD000002,2025-01-01,CUST00076,36,Female,Loyal,Jaipur,Rajasthan,P004,Scented Candle,Home & Office,1,249,399,15,37.35,50,211.65,261.65,Cash on Delivery,WhatsApp,Referral,Delivered,2025-01-07,6.0,NaN
2,ORD000003,2025-01-01,CUST00111,29,Male,New,Bengaluru,Karnataka,P001,Reusable Water Bottle,Lifestyle,2,299,499,0,0.00,50,598.00,648.00,Debit Card,Instagram,Organic Search,Delivered,2025-01-03,2.0,4.0
3,ORD000004,2025-01-01,CUST00111,29,Male,New,Bengaluru,Karnataka,P001,Reusable Water Bottle,Lifestyle,2,299,499,5,29.90,50,568.10,618.10,Debit Card,Marketplace,Direct,Delivered,2025-01-05,4.0,4.0
4,ORD000005,2025-01-02,CUST00391,23,Female,New,Jaipur,Rajasthan,P008,Travel Pouch,Accessories,1,329,499,5,16.45,60,312.55,372.55,Net Banking,Website,Organic Search,Delivered,2025-01-05,3.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1493,ORD001494,2025-12-28,CUST00594,33,Male,New,Mumbai,Maharashtra,P004,Scented Candle,Home & Office,2,249,399,10,49.80,0,448.20,448.20,Cash on Delivery,WhatsApp,Direct,Delivered,2025-12-31,3.0,4.0
1494,ORD001495,2025-12-29,CUST00111,29,Male,New,Bengaluru,Karnataka,P001,Reusable Water Bottle,Lifestyle,2,299,499,10,59.80,60,538.20,598.20,Credit Card,WhatsApp,Instagram Ads,Delivered,2026-01-02,4.0,5.0
1496,ORD001497,2025-12-29,CUST00302,29,Female,Returning,Surat,Gujarat,P009,Ceramic Mug,Home & Office,1,279,449,10,27.90,60,251.10,311.10,Credit Card,Instagram,Instagram Ads,Delivered,2026-01-03,5.0,5.0
1498,ORD001499,2025-12-30,CUST00063,22,Male,Returning,Kota,Rajasthan,P011,Resistance Band Set,Fitness,1,499,799,15,74.85,50,424.15,474.15,Net Banking,Instagram,Organic Search,Delivered,2026-01-06,7.0,4.0
1499,ORD001500,2025-12-31,CUST00673,28,Female,Returning,Delhi,Delhi,P001,Reusable Water Bottle,Lifestyle,1,299,499,20,59.80,0,239.20,239.20,Cash on Delivery,Instagram,Instagram Ads,Delivered,2026-01-05,5.0,NaN

In [48]:
delivered_df.groupby('gender')['customer_rating'].mean()

gender
Female    3.953431
Male      3.843972
Unknow    3.800000
Name: customer_rating, dtype: float64

In [49]:
delivered_df["customer_rating"] = delivered_df.groupby("gender")["customer_rating"].transform(
    lambda x: x.fillna(round(x.mean(), 1))
)

In [50]:
delivered_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1215 entries, 0 to 1499
Data columns (total 26 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   order_id                 1215 non-null   object
 1   order_date               1215 non-null   object
 2   customer_id              1215 non-null   object
 3   customer_age             1215 non-null   int64
 4   gender                   1215 non-null   object
 5   customer_segment         1215 non-null   object
 6   city                     1215 non-null   object
 7   state                    1215 non-null   object
 8   product_id               1215 non-null   object
 9   product_name             1215 non-null   object
 10  category                 1215 non-null   object
 11  quantity                 1215 non-null   int64
 12  unit_price_inr           1215 non-null   int64
 13  original_unit_price_inr  1215 non-null   int64
 14  discount_percent         1215 non-null   int64
 15  discount_amount_inr      1215 non-null   float64
 16  shipping_cost_inr        1215 non-null   int64
 17  order_value_inr          1215 non-null   float64
 18  total_amount_inr         1215 non-null   float64
 19  payment_mode             1215 non-null   object
 20  sales_channel            1215 non-null   object
 21  acquisition_source       1215 non-null   object
 22  order_status             1215 non-null   object
 23  delivery_date            1215 non-null   object
 24  delivery_days            1215 non-null   float64
 25  customer_rating          1215 non-null   float64
dtypes: float64(5), int64(6), object(15)
memory usage: 256.3+ KB

In [51]:
delivered_df['order_date'] = pd.to_datetime(delivered_df['order_date'])
delivered_df['delivery_date'] = pd.to_datetime(delivered_df['delivery_date'])